"""add_task_position_for_manual_ordering

Revision ID: 2e7ec7d32bb5
Revises: c94f2dc8c4c0
Create Date: 2026-10-06 20:01:53.626201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7ec7d32bb5'
down_revision = 'c94f2dc8c4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # server_default='0' evita violar el NOT NULL sobre las tareas ya creadas en
        # los Incrementos 1 a 4. Todas quedan en la posición 0 y, como el desempate
        # del listado es created_at DESC, conservan exactamente el orden que tenían
        # hasta que el usuario arrastre algo por primera vez (FR-011, SC-005).
        batch_op.add_column(
            sa.Column('position', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_tasks_position'), ['position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_position'))
        batch_op.drop_column('position')

    # ### end Alembic commands ###
