"""add_categories_priority_and_task_category_link

Revision ID: 735d39529a04
Revises: f2a89c1d3e4b
Create Date: 2026-10-06 19:26:04.914492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735d39529a04'
down_revision = 'f2a89c1d3e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_category_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        # server_default garantiza que las tareas ya creadas en los Incrementos 1 y 2
        # queden con la prioridad por defecto en vez de violar el NOT NULL (FR-002).
        batch_op.add_column(
            sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium')
        )
        batch_op.create_index(batch_op.f('ix_tasks_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        # La clave foránea se nombra explícitamente: sin nombre, el downgrade falla
        # porque SQLite no puede resolver un drop_constraint(None).
        batch_op.create_foreign_key(
            'fk_tasks_category_id', 'categories', ['category_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_category_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_category_id'))
        batch_op.drop_column('priority')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
