"""add_task_assignment_and_notifications

Revision ID: c94f2dc8c4c0
Revises: 735d39529a04
Create Date: 2026-10-06 19:45:52.582810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94f2dc8c4c0'
down_revision = '735d39529a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # Las claves foráneas se nombran explícitamente: sin nombre, un downgrade
    # posterior no puede resolver drop_constraint(None) en SQLite.
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='fk_notifications_recipient_id'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_notifications_sender_id'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_notifications_task_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_tasks_assigned_to_id', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_assigned_to_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to_id'))
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
