"""orden manual persistente de tareas

Revision ID: d788c6326639
Revises: bdf9ad1d98c7
Create Date: 2026-10-07 18:14:16.230466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd788c6326639'
down_revision = 'bdf9ad1d98c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_tasks_manual_order'), ['manual_order'], unique=False)

    # ### end Alembic commands ###

    # Backfill determinista: manual_order secuencial por usuario siguiendo created_at
    # descendente (mismo orden que ya se lista por defecto), ver research.md §5.
    from src.taskcontrol.services.task_service import TaskService

    TaskService.backfill_manual_order()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_manual_order'))
        batch_op.drop_column('manual_order')

    # ### end Alembic commands ###
